config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord

    def full_name
    "#{first_name} #{last_name}"
  end

     def location
    "#{city} #{state}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:first_name, :last_name, :phone, :city, :state, :email, :active, :load, :status, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
    <%= simple_form_for(@driver) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div id="form-col-1">

  <div class="form-group">
    <%= form.label :full_name, "Name", class: "form-label" %>
    <%= form.text_field :full_name, id: :driver_first_name, class: "form-control name" %>
  </div>



  <div class="form-group">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, id: :driver_phone, class: "form-control name" %>
  </div>

<div class="form-group">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, id: :driver_email, class: "form-control name" %>
  </div>

  <div class="form-group">
    <%= form.label :location, class: "form-label" %>
    <%= form.text_field :location, id: :driver_city, class: "form-control name" %>
  </div>




</div>
  <div id="form-col-2">






  <div class="form-group">
    <%= form.label :load, class: "form-label" %>
    <%= form.text_field :load, id: :driver_load, class: "form-control name" %>
  </div>

  <div class="form-group">
    <%= form.label :status, class: "form-label" %>
    <%= form.text_field :status, id: :driver_status, class: "form-control name" %>
  </div>

  <div class="form-group">
    <%= form.label :comments, class: "form-label" %>
    <%= form.text_field :comments, id: :driver_comments, class: "form-control name" %>
  </div>

   <div class="form-group">
    <%= form.label :active, class: "form-label" %>
    <%= form.check_box :active, id: :driver_active, class: "form-control name" %>
  </div>
</div>
  <div class="actions">
    <%= form.button :submit, class: "btn btn-success" %>
    <%= link_to 'Show', @driver, class: "btn btn-success" %>
    <%= link_to 'Back', drivers_path,  class: "btn btn-success"  %>
  </div>



<% end %>

app/views/drivers/edit.html.erb
<div class="container driver-container">
  <div>
    <div>
      <div class="page-header">
        <h1>Editing Driver</h1>
      </div>
    </div>
  </div>
  <%= render 'form', driver: @driver %>
</div>

app/views/drivers/index.html.erb
<div class="jumbotron jumbotron-home">

        <h1>Driver Tracking</h1>

</div>




<div id = "driv-feed">
 <table class="table table-bordered table-hover">
    <thead>
      <tr>

        <th>Driver Name</th>
        <th>Phone</th>
        <th>City</th>
        <th>State</th>
        <th>Email</th>
        <th>Active</th>
        <th>Driver status</th>
        <th>Company</th>
        <th>Comments</th>
        <th> Update Driver</th>

      </tr>
    </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.full_name %></td>
        <td><%= driver.phone %></td>
        <td><%= driver.city %></td>
        <td><%= driver.state %></td>
        <td><%= driver.email %></td>
        <td><%= driver.active %></td>
        <td><%= driver.load %></td>
        <td><%= driver.status %></td>
        <td><%= driver.comments %></td>
        <td><%= link_to 'Show', driver, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_driver_path(driver), class: "btn btn-warning btn-group"  %>
        <%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/drivers/new.html.erb
<div class="container driver-container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>New Driver</h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
<%= render 'form', driver: @driver %>    </div>
  </div>
</div>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @driver.full_name %></h1>

  <table id="show-table" class="table table-bordered">
<tr>

<td>
  <strong>Phone:</strong>
  <%= @driver.phone %>
</td>

<td>
  <strong>City:</strong>
  <%= @driver.city %>
</td>

<td>
  <strong>State:</strong>
  <%= @driver.state %>
</td>

<td>
  <strong>Email:</strong>
  <%= @driver.email %>
</td>

<td>
  <strong>Active:</strong>
  <%= @driver.active %>
</td>

<td>
  <strong>Load:</strong>
  <%= @driver.load %>
</td>

<td>
  <strong>Status:</strong>
  <%= @driver.status %>
</td>

<td>
  <strong>Comments:</strong>
  <%= @driver.comments %>
</td>
   </tbody>
  </table>
<%= link_to 'Edit', edit_driver_path(@driver), class: "btn btn-warning" %>
<%= link_to 'Home', drivers_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drivertracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", drivers_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'New Driver', new_driver_path, class: "nav-link" %></li>
        </ul>
      </div>
    </nav>
  <body>
    <%= yield %>
  </body>
</html>